// Package shell generates the sourced shell-integration snippet for bash, zsh,
// and fish (SPEC.md §3.2). The generated functions wrap the user's enabled
// commands, delegate the decision to `safu guard`, and — critically — fall
// through to the real command if safu is disabled, missing, or errors
// (fail-open, invariant #3).
//
// The `safu guard` subcommand itself lands in a later slice; this package only
// generates the text that will call it. The exit-code contract below is the
// interface guard must honor.
package shell

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
	"text/template"
)

// Guard exit-code contract (consumed by the generated snippet):
//
//	0          -> approved: run the real command
//	ExitBlock  -> blocked: abort, do not run the real command
//	any other  -> safu errored: fail open, run the real command anyway
const ExitBlock = 10

// Shell identifies a supported shell.
type Shell string

const (
	Bash Shell = "bash"
	Zsh  Shell = "zsh"
	Fish Shell = "fish"
)

// Parse validates a shell name.
func Parse(s string) (Shell, error) {
	switch Shell(strings.ToLower(strings.TrimSpace(s))) {
	case Bash:
		return Bash, nil
	case Zsh:
		return Zsh, nil
	case Fish:
		return Fish, nil
	default:
		return "", fmt.Errorf("unsupported shell %q (want bash|zsh|fish)", s)
	}
}

// ruleToCommand maps a guard rule id from config (guard.wrapped) to the actual
// shell command that must be wrapped. Several rules collapse onto one command
// (e.g. git-push-force -> git); the guard classifies the specifics.
var ruleToCommand = map[string]string{
	"rm":             "rm",
	"dd":             "dd",
	"mkfs":           "mkfs",
	"git-push-force": "git",
	"chmod-r":        "chmod",
	"chown-r":        "chown",
}

// neverWrap lists shell-critical commands safu must never shadow (SPEC.md §3.3).
var neverWrap = map[string]bool{
	"sh": true, "bash": true, "zsh": true, "fish": true,
	"env": true, "exec": true, "command": true, "safu": true,
}

// Commands resolves the config rule ids into the de-duplicated, sorted list of
// real shell commands to wrap, dropping any shell-critical names.
func Commands(wrapped []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, rule := range wrapped {
		cmd, ok := ruleToCommand[rule]
		if !ok {
			cmd = rule // unknown rule: wrap the literal name
		}
		if neverWrap[cmd] || seen[cmd] {
			continue
		}
		seen[cmd] = true
		out = append(out, cmd)
	}
	sort.Strings(out)
	return out
}

type tmplData struct {
	Commands  []string
	ExitBlock int
}

// Snippet generates the full sourced snippet for sh wrapping the given config
// rule ids.
func Snippet(sh Shell, wrapped []string) (string, error) {
	t, ok := templates[sh]
	if !ok {
		return "", fmt.Errorf("unsupported shell %q", sh)
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, tmplData{Commands: Commands(wrapped), ExitBlock: ExitBlock}); err != nil {
		return "", fmt.Errorf("generate %s snippet: %w", sh, err)
	}
	return buf.String(), nil
}

var templates = map[Shell]*template.Template{
	Bash: template.Must(template.New("bash").Parse(posixTemplate)),
	Zsh:  template.Must(template.New("zsh").Parse(posixTemplate)),
	Fish: template.Must(template.New("fish").Parse(fishTemplate)),
}

// posixTemplate covers bash and zsh (identical POSIX function syntax here).
const posixTemplate = `# safu shell integration — source this from your rc file.
# Generated by ` + "`safu init`" + `. Set SAFU_DISABLE=1 to bypass entirely.
{{range .Commands}}
{{.}}() {
  if [ -z "$SAFU_DISABLE" ] && command -v safu >/dev/null 2>&1; then
    safu guard --as {{.}} -- "$@"
    __safu_rc=$?
    if [ "$__safu_rc" -eq {{$.ExitBlock}} ]; then
      return {{$.ExitBlock}}
    fi
  fi
  command {{.}} "$@"
}
{{end}}`

const fishTemplate = `# safu shell integration — source this from config.fish.
# Generated by ` + "`safu init`" + `. Set SAFU_DISABLE=1 to bypass entirely.
{{range .Commands}}
function {{.}}
  if test -z "$SAFU_DISABLE"; and type -q safu
    safu guard --as {{.}} -- $argv
    if test $status -eq {{$.ExitBlock}}
      return {{$.ExitBlock}}
    end
  end
  command {{.}} $argv
end
{{end}}`
